name: Maven CI

on:
  workflow_dispatch: { }
  push:
    branches-ignore:
      - 'renovate/*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: ./mvnw --show-version --errors --batch-mode --no-transfer-progress verify -Pdocs #,dockerize

